# Copyright (C) 2025 Miguel Ángel González Santamarta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Dict, Iterator, List, Tuple, overload

class Blackboard:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: "Blackboard") -> None: ...
    def copy(self) -> "Blackboard": ...
    def set(self, key: str, value: Any) -> None: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __setattr__(self, name, value): ...
    def get(self, key: str) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def __getattr__(self, name): ...
    def remove(self, key: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def contains(self, key: str) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[Any]: ...
    def items(self) -> List[Tuple[str, Any]]: ...
    def __iter__(self) -> Iterator[str]: ...
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    def set_remappings(self, remappings: Dict[str, str]) -> None: ...
    def get_remappings(self) -> Dict[str, str]: ...
