# Copyright (C) 2025 Miguel Ángel González Santamarta
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Dict

class Blackboard:
    def __init__(self) -> None: ...
    def set(self, key: str, value: Any) -> None: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __setattr__(self, name, value): ...
    def get(self, key: str) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def __getattr__(self, name): ...
    def remove(self, key: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def contains(self, key: str) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    def set_remappings(self, remappings: Dict[str, str]) -> None: ...
    def get_remappings(self) -> Dict[str, str]: ...
