# Copyright (C) 2026 Miguel Ángel González Santamarta
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Callable

class CallbackSignalFuture:
    def wait(self) -> None: ...
    def is_completed(self) -> bool: ...
    def has_exception(self) -> bool: ...
    def get_exception_message(self) -> str: ...

class CallbackSignal:
    def __init__(self) -> None: ...
    def add_callback(self, callback: Callable[[], None]) -> int: ...
    def add_cancel_callback(self, state) -> int: ...
    def remove_callback(self, callback_id: int) -> bool: ...
    def clear_callbacks(self) -> None: ...
    def callback_count(self) -> int: ...
    def empty(self) -> bool: ...
    def trigger(self) -> None: ...
    def trigger_async(self) -> CallbackSignalFuture: ...
