# Copyright (C) 2026 Miguel Ángel González Santamarta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Callable

class CallbackSignalFuture:
    def wait(self) -> None: ...
    def is_completed(self) -> bool: ...
    def has_exception(self) -> bool: ...
    def get_exception_message(self) -> str: ...

class CallbackSignal:
    def __init__(self) -> None: ...
    def add_callback(self, callback: Callable[[], None]) -> int: ...
    def add_cancel_callback(self, state) -> int: ...
    def remove_callback(self, callback_id: int) -> bool: ...
    def clear_callbacks(self) -> None: ...
    def callback_count(self) -> int: ...
    def empty(self) -> bool: ...
    def trigger(self) -> None: ...
    def trigger_async(self) -> CallbackSignalFuture: ...
