from typing import Callable

class CallbackSignalFuture:
    def wait(self) -> None: ...
    def is_completed(self) -> bool: ...
    def has_exception(self) -> bool: ...
    def get_exception_message(self) -> str: ...

class CallbackSignal:
    def __init__(self) -> None: ...
    def add_callback(self, callback: Callable[[], None]) -> int: ...
    def add_cancel_callback(self, state) -> int: ...
    def remove_callback(self, callback_id: int) -> bool: ...
    def clear_callbacks(self) -> None: ...
    def callback_count(self) -> int: ...
    def empty(self) -> bool: ...
    def trigger(self) -> None: ...
    def trigger_async(self) -> CallbackSignalFuture: ...
