# Copyright (C) 2025 Miguel Ángel González Santamarta
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from enum import Enum
from typing import List, Set, overload
from yasmin.blackboard import Blackboard

class StateStatus(Enum):
    IDLE: int
    RUNNING: int
    CANCELED: int
    COMPLETED: int

class State:
    @overload
    def __init__(self, outcomes: Set[str]) -> None: ...
    @overload
    def __init__(self, outcomes: List[str]) -> None: ...
    def get_status(self) -> StateStatus: ...
    def is_idle(self) -> bool: ...
    def is_running(self) -> bool: ...
    def is_canceled(self) -> bool: ...
    def is_completed(self) -> bool: ...
    def execute(self, blackboard: Blackboard) -> str: ...
    def cancel_state(self) -> None: ...
    def get_outcomes(self) -> Set[str]: ...
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    def __call__(self, blackboard: Blackboard) -> str: ...
