# Copyright (C) 2025 Miguel Ángel González Santamarta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Callable, Dict, List, Set, overload
from yasmin.state import State
from yasmin import Blackboard

class StateMachine(State):
    @overload
    def __init__(self, outcomes: Set[str]) -> None: ...
    @overload
    def __init__(self, outcomes: List[str], handle_sigint: bool = False) -> None: ...
    @overload
    def __init__(
        self, name: str, outcomes: Set[str], handle_sigint: bool = False
    ) -> None: ...
    @overload
    def __init__(
        self, name: str, outcomes: List[str], handle_sigint: bool = False
    ) -> None: ...
    def add_state(
        self,
        name: str,
        state: State,
        transitions: Dict[str, str] = ...,
        remappings: Dict[str, str] = ...,
        parameter_mappings: Dict[str, str] = ...,
    ) -> None: ...
    def set_name(self, name: str) -> None: ...
    def get_name(self) -> str: ...
    def set_start_state(self, state_name: str) -> None: ...
    def get_start_state(self) -> str: ...
    def get_states(self) -> Dict[str, Dict[str, Any]]: ...
    def _get_states_cpp(self) -> Dict[str, State]: ...
    def get_transitions(self) -> Dict[str, Dict[str, str]]: ...
    def get_current_state(self) -> str: ...
    def add_start_cb(self, cb: Callable[[Blackboard, str], None]) -> None: ...
    def add_transition_cb(
        self, cb: Callable[[Blackboard, str, str, str], None]
    ) -> None: ...
    def add_end_cb(self, cb: Callable[[Blackboard, str], None]) -> None: ...
    def set_parameter_mappings(
        self, state_name: str, parameter_mappings: Dict[str, str]
    ) -> None: ...
    def get_parameter_mappings(self) -> Dict[str, Dict[str, str]]: ...
    def validate(self, strict_mode: bool = False) -> None: ...
    def configure(self) -> None: ...
    def cancel_state(self) -> None: ...
    def cancel_state_machine(self) -> None: ...
    def set_sigint_handler(self, handle: bool = True) -> None: ...
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    def __call__(self, blackboard: Blackboard) -> str: ...
