# Copyright (C) 2025 Miguel Ángel González Santamarta
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Dict, List, Optional, Set, overload

from yasmin import Blackboard

class State:
    @overload
    def __init__(self, outcomes: Set[str]) -> None: ...
    @overload
    def __init__(self, outcomes: List[str]) -> None: ...
    def is_idle(self) -> bool: ...
    def is_running(self) -> bool: ...
    def is_canceled(self) -> bool: ...
    def is_completed(self) -> bool: ...
    def execute(self, blackboard: Blackboard) -> str: ...
    def cancel_state(self) -> None: ...
    def get_outcomes(self) -> Set[str]: ...
    def set_description(self, description: str) -> None: ...
    def get_description(self) -> str: ...
    def set_outcome_description(self, outcome: str, description: str) -> None: ...
    def get_outcome_description(self, outcome: str) -> str: ...
    def get_outcome_descriptions(self) -> Dict[str, str]: ...
    @overload
    def add_input_key(self, key_name: str) -> None: ...
    @overload
    def add_input_key(self, key_name: str, description: str) -> None: ...
    @overload
    def add_input_key(
        self, key_name: str, description: str, default_value: Any
    ) -> None: ...
    @overload
    def add_output_key(self, key_name: str) -> None: ...
    @overload
    def add_output_key(self, key_name: str, description: str) -> None: ...
    def get_input_keys(self) -> List[Dict]: ...
    def get_output_keys(self) -> List[Dict]: ...
    def get_metadata(self) -> Dict: ...
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    def __call__(self, blackboard: Optional[Blackboard] = None) -> str: ...
