# Copyright (C) 2025 Miguel Ángel González Santamarta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Dict, List, Optional, Set, overload

from yasmin import Blackboard

class State:
    @overload
    def __init__(self, outcomes: Set[str]) -> None: ...
    @overload
    def __init__(self, outcomes: List[str]) -> None: ...
    def is_idle(self) -> bool: ...
    def is_running(self) -> bool: ...
    def is_canceled(self) -> bool: ...
    def is_completed(self) -> bool: ...
    def execute(self, blackboard: Blackboard) -> str: ...
    def configure(self) -> None: ...
    def cancel_state(self) -> None: ...
    def get_outcomes(self) -> Set[str]: ...
    def set_description(self, description: str) -> None: ...
    def get_description(self) -> str: ...
    def set_outcome_description(self, outcome: str, description: str) -> None: ...
    def get_outcome_description(self, outcome: str) -> str: ...
    def get_outcome_descriptions(self) -> Dict[str, str]: ...
    @overload
    def add_input_key(self, key_name: str) -> None: ...
    @overload
    def add_input_key(self, key_name: str, description: str) -> None: ...
    @overload
    def add_input_key(
        self, key_name: str, description: str, default_value: Any
    ) -> None: ...
    @overload
    def add_output_key(self, key_name: str) -> None: ...
    @overload
    def add_output_key(self, key_name: str, description: str) -> None: ...
    @overload
    def declare_parameter(self, parameter_name: str) -> None: ...
    @overload
    def declare_parameter(self, parameter_name: str, description: str) -> None: ...
    @overload
    def declare_parameter(
        self, parameter_name: str, description: str, default_value: Any
    ) -> None: ...
    def has_parameter(self, parameter_name: str) -> bool: ...
    def get_parameter(self, parameter_name: str) -> Any: ...
    def set_parameter(self, parameter_name: str, value: Any) -> None: ...
    def get_parameters(self) -> List[Dict]: ...
    def get_input_keys(self) -> List[Dict]: ...
    def get_output_keys(self) -> List[Dict]: ...
    def get_metadata(self) -> Dict: ...
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    def __call__(self, blackboard: Optional[Blackboard] = None) -> str: ...
