# Copyright (C) 2025 Miguel Ángel González Santamarta
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Callable, Dict, List, Set, overload, Any
from yasmin.state import State
from yasmin.blackboard import Blackboard

class StateMachine(State):
    @overload
    def __init__(self, outcomes: Set[str]) -> None: ...
    @overload
    def __init__(self, outcomes: List[str]) -> None: ...
    def add_state(
        self,
        name: str,
        state: State,
        transitions: Dict[str, str] = {},
        remappings: Dict[str, str] = {},
    ) -> None: ...
    def set_name(self, name: str) -> None: ...
    def get_name(self) -> str: ...
    def set_start_state(self, state_name: str) -> None: ...
    def get_start_state(self) -> str: ...
    def get_states(self) -> Dict[str, Dict[str, Any]]: ...
    def _get_states_cpp(self) -> Dict[str, State]: ...
    def get_transitions(self) -> Dict[str, Dict[str, str]]: ...
    def get_current_state(self) -> str: ...
    def add_start_cb(
        self, cb: Callable[[Blackboard, str, List[str]], None], args: List[str] = []
    ) -> None: ...
    def add_transition_cb(
        self,
        cb: Callable[[Blackboard, str, str, str, List[str]], None],
        args: List[str] = [],
    ) -> None: ...
    def add_end_cb(
        self, cb: Callable[[Blackboard, str, List[str]], None], args: List[str] = []
    ) -> None: ...
    def validate(self, strict_mode: bool = False) -> None: ...
    def cancel_state(self) -> None: ...
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    def __call__(self, blackboard: Blackboard) -> str: ...
