name: Kilted Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  kilted_build_and_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: kilted
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: yasmin yasmin_ros
          target-ros2-distro: kilted
