name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - humble
          - iron
          - jazzy
          - kilted
          - rolling
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: yasmin yasmin_ros
          target-ros2-distro: ${{ matrix.ros_distribution }}
