name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  unit_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu:jammy]
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: yasmin yasmin_ros
          target-ros2-distro: humble
